services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NGINX-Proxy-Manager
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - NginxProxyManager:/data
      - NginxProxyManager:/etc/letsencrypt

volumes:
  NginxProxyManager:

networks:
  proxy:
    external: true
