version: "3.4"
services:
  db:
    container_name: influxdb
    image: influxdb:2.7.1-alpine
    restart: unless-stopped
    volumes:
      - /mnt/docker/grafana-influxdb/influxdb:/var/lib/influxdb2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}

  dashboard:
    container_name: grafana
    image: grafana/grafana-oss:main
    restart: unless-stopped
    volumes:
      - /mnt/docker/grafana-influxdb/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - db