version: "2"
services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - API_KEY=${CLOUDFLARE_API_KEY}
      - ZONE=${CLOUDFLARE_ZONE}
      # Verwende den Cloudflare Proxy, damit wird deine IP Adresse verborgen, der Verkehr geht allerdings über die Cloudflare Server
      - PROXIED=true