---
- name: Configure system and create user
  hosts: linux
  remote_user: wiecktim
  become: true
  tasks:
    - name: Disable SSH password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: "PasswordAuthentication no"
        state: present
        backup: yes
      notify:
        - Restart SSH service

    - name: Disable root login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify:
        - Restart SSH service

  handlers:
    - name: Restart SSH service
      service:
        name: sshd
        state: restarted

