---
- name: Aktualisiere Linux Server über APT
  hosts: ubuntu:raspbian
  become: yes
  tasks:
    - name: Update-Paketliste
      apt:
        update_cache: yes
      register: update_result

    - name: Führe APT-Upgrade durch
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
      when: update_result.changed
      register: upgrade_result

    - name: Starte den Server neu
      reboot:
      when: upgrade_result.changed