version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /mnt/docker/heimdall/config:/config
    ports:
      - 840:80
      - 4443:443
    restart: unless-stopped