version: "3"
services:
  bookstack:
    container_name: bookstack
    image: linuxserver/bookstack
    restart: unless-stopped
    volumes:
      - App:/config
    ports:
      - ${PORT}:80
    environment:
      - APP_URL=${BOOKSTACK_APP_URL}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${BOOKSTACK_MYSQL_PASSWORD}
      - DB_DATABASE=bookstackapp
    depends_on:
      - bookstack_db

  bookstack_db:
    container_name: bookstack_db
    image: linuxserver/mariadb
    restart: unless-stopped
    volumes:
      - DB:/config
    environment:
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${BOOKSTACK_MYSQL_PASSWORD}

volumes:
  App:
  DB: