version: "3"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - APP_URL=${BOOKSTACK_APP_URL}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=${BOOKSTACK_MYSQL_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/docker/bookstack/app:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_MYSQL_ROOT_PASSWORD}
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${BOOKSTACK_MYSQL_PASSWORD}
    volumes:
      - /mnt/docker/bookstack/db:/config
    restart: unless-stopped