version: "3.1"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - Vaultwarden::/app/data

volumes:
  Vaultwarden:

networks:
  proxy:
    external: true