version: "3.1"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - Uptime-Kuma:/app/data

volumes:
  Uptime-Kuma:

networks:
  proxy:
    external: true