version: "3.1"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /mnt/docker/uptimekuma/:/app/data

networks:
  proxy:
    external: true