version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    volumes:
      - /mnt/docker/pihole/etc-pihole:/etc/pihole
      - /mnt/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: '${PIHOLE_WEBPASSWORD}'