---
- name: Enable Kernel Module ip_vs
  hosts: docker
  become: true
  tasks:
   - name: Enable ip_vs Kernel module
     lineinfile:
      dest: /etc/modules
      regexp: 'modprobe ip_vs'
      line: 'modprobe ip_vs'
      state: present

   - name: Starte den Server neu
     reboot: