---
- name: Mount Docker Storage
  hosts: docker
  become: true
  tasks: 
    - name: Install nfs-common
      apt:
        name: nfs-common
        update_cache: yes
        
    - name: Mount NFS Share at boot
      ansible.posix.mount:
        src: "{{ remotedockerstorage }}"
        path: /mnt/docker
        opts: auto
        boot: true
        state: mounted
        fstype: nfs