---
- name: SSH Configuration
  hosts: ubuntu
  become: true
  tasks:
    - name: Check if SSH key pair exists
      stat:
        path: /home/{{ remoteuser }}/.ssh/authorized_keys
      register: ssh_key

    - name: Disable SSH password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: restart sshd
      when: ssh_key.stat.exists
      
    - name: Remove line from sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^Include /etc/ssh/sshd_config.d/\*.conf'
        state: absent  
      notify: restart sshd
      when: ssh_key.stat.exists

    - name: Disable root SSH login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted