---
- name: Enable Hotplug for eth0 for raspbian 
  hosts: raspbian
  become: true
  tasks:
    - name: Add line to /etc/network/interfaces
      lineinfile:
        dest: /etc/network/interfaces
        regexp: 'allow-hotplug eth0'
        line: 'allow-hotplug eth0'
        state: present